interface LearningReport {
  userName: string;
  totalNotes: number;
  totalProjects: number;
  totalBookmarks: number;
  breakthroughs: number;
  topCategories: string[];
  joinDate: string;
  notes: Array<{ title: string; type: string; date: string }>;
  projects: Array<{ name: string; status: string; progress: number }>;
}

export const generateLearningReportHTML = (report: LearningReport): string => {
  const completedProjects = report.projects.filter(p => p.status === 'Completed').length;
  const activeProjects = report.projects.filter(p => p.status !== 'Completed').length;

  return `<!DOCTYPE html>
<html><head><title>Learning Report - ${report.userName}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;700&family=Inter:wght@300;400;500;600&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', sans-serif; color: #1a1a2e; padding: 40px; max-width: 900px; margin: 0 auto; background: #fff; }
  .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #c9a84c; padding-bottom: 30px; }
  .header h1 { font-family: 'Space Grotesk', sans-serif; font-size: 32px; color: #1a1a2e; }
  .header .subtitle { color: #666; font-size: 14px; margin-top: 8px; }
  .header .badge { display: inline-block; background: #c9a84c; color: #fff; padding: 4px 16px; border-radius: 20px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 2px; margin-top: 12px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 40px; }
  .stat { text-align: center; padding: 20px; border: 1px solid #e5e5e5; border-radius: 12px; }
  .stat .value { font-family: 'Space Grotesk'; font-size: 36px; font-weight: 700; color: #c9a84c; }
  .stat .label { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; color: #888; margin-top: 4px; }
  .section { margin-bottom: 30px; }
  .section h2 { font-family: 'Space Grotesk'; font-size: 18px; border-bottom: 1px solid #e5e5e5; padding-bottom: 8px; margin-bottom: 16px; color: #1a1a2e; }
  .item { padding: 12px 16px; border-left: 3px solid #c9a84c; margin-bottom: 8px; background: #fafafa; border-radius: 0 8px 8px 0; }
  .item .title { font-weight: 600; font-size: 14px; }
  .item .meta { font-size: 11px; color: #888; margin-top: 2px; }
  .progress-bar { height: 6px; background: #e5e5e5; border-radius: 3px; overflow: hidden; margin-top: 6px; }
  .progress-fill { height: 100%; background: #c9a84c; border-radius: 3px; }
  .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e5e5; font-size: 10px; color: #aaa; }
  @media print { body { padding: 20px; } }
</style></head><body>
<div class="header">
  <h1>📊 Research Learning Report</h1>
  <div class="subtitle">${report.userName} · Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  <div class="badge">Nobel Hub Nexus Scholar</div>
</div>

<div class="stats">
  <div class="stat"><div class="value">${report.totalNotes}</div><div class="label">Lab Notes</div></div>
  <div class="stat"><div class="value">${report.totalProjects}</div><div class="label">Projects</div></div>
  <div class="stat"><div class="value">${report.breakthroughs}</div><div class="label">Breakthroughs</div></div>
  <div class="stat"><div class="value">${report.totalBookmarks}</div><div class="label">Bookmarks</div></div>
</div>

<div class="section">
  <h2>📋 Research Projects (${activeProjects} active, ${completedProjects} completed)</h2>
  ${report.projects.map(p => `
    <div class="item">
      <div class="title">${p.name}</div>
      <div class="meta">${p.status} · ${p.progress}% complete</div>
      <div class="progress-bar"><div class="progress-fill" style="width:${p.progress}%"></div></div>
    </div>`).join('')}
  ${report.projects.length === 0 ? '<div class="item"><div class="meta">No projects yet</div></div>' : ''}
</div>

<div class="section">
  <h2>📝 Recent Lab Notes</h2>
  ${report.notes.slice(0, 10).map(n => `
    <div class="item">
      <div class="title">${n.title}</div>
      <div class="meta">${n.type.toUpperCase()} · ${n.date}</div>
    </div>`).join('')}
  ${report.notes.length === 0 ? '<div class="item"><div class="meta">No notes yet</div></div>' : ''}
</div>

<div class="footer">
  Generated by Nobel Hub Nexus · PhD Research Operating System · Member since ${report.joinDate}
</div>
<script>window.onload=()=>{window.print();}</script>
</body></html>`;
};

interface CertificateData {
  userName: string;
  category: string;
  completedCount: number;
  totalCount: number;
  date: string;
}

export const generateCertificateHTML = (cert: CertificateData): string => {
  return `<!DOCTYPE html>
<html><head><title>Certificate of Completion - ${cert.category}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;700&family=Playfair+Display:ital,wght@0,400;0,700;1,400&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; background: #f5f5f5; font-family: 'Inter', sans-serif; }
  .cert { width: 800px; padding: 60px; background: linear-gradient(135deg, #fffdf7 0%, #fff9e6 100%); border: 3px solid #c9a84c; border-radius: 4px; text-align: center; position: relative; }
  .cert::before { content: ''; position: absolute; inset: 8px; border: 1px solid #c9a84c40; border-radius: 2px; }
  .logo { font-family: 'Space Grotesk', sans-serif; font-size: 14px; font-weight: 700; letter-spacing: 6px; text-transform: uppercase; color: #c9a84c; margin-bottom: 30px; }
  .title { font-family: 'Playfair Display', serif; font-size: 42px; color: #1a1a2e; margin-bottom: 10px; }
  .subtitle { font-size: 16px; color: #666; margin-bottom: 40px; }
  .name { font-family: 'Playfair Display', serif; font-size: 36px; font-style: italic; color: #c9a84c; border-bottom: 2px solid #c9a84c; display: inline-block; padding-bottom: 8px; margin-bottom: 30px; }
  .desc { font-size: 14px; color: #555; line-height: 1.8; max-width: 500px; margin: 0 auto 30px; }
  .badge { display: inline-block; background: #c9a84c; color: #fff; padding: 8px 24px; border-radius: 4px; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 2px; }
  .meta { margin-top: 40px; font-size: 11px; color: #999; }
  @media print { body { background: #fff; } .cert { box-shadow: none; } }
</style></head><body>
<div class="cert">
  <div class="logo">Nobel Hub Nexus</div>
  <div class="title">Certificate of Completion</div>
  <div class="subtitle">${cert.category} Category Mastery</div>
  <div class="name">${cert.userName}</div>
  <div class="desc">
    Has demonstrated exceptional scholarly dedication by exploring and studying
    <strong>${cert.completedCount}</strong> Nobel laureates in the <strong>${cert.category}</strong> category,
    completing the full learning path with distinction.
  </div>
  <div class="badge">🏅 ${cert.category} Scholar</div>
  <div class="meta">Issued: ${cert.date} · Nobel Hub Nexus Research Platform</div>
</div>
<script>window.onload=()=>{window.print();}</script>
</body></html>`;
};

export const openPrintWindow = (html: string) => {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
};
