import { motion } from "framer-motion";
import { User, Bookmark, Clock, Settings, LogOut, ChevronRight, Award, BookOpen, Video, Sparkles, FolderKanban, FileEdit, Plus, Trash2, ExternalLink, Share2, Download } from "lucide-react";
import PageLayout from "@/frontend/components/layout/PageLayout";
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useNavigate, Link } from "react-router-dom";
import { toast } from "sonner";
import { useAuth } from "@/App";
import { useScholarData, LabNote } from "@/frontend/hooks/useScholarData";
import ReactMarkdown from "react-markdown";
import {
    Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";

const Profile = () => {
    const { session } = useAuth();
    const [activeTab, setActiveTab] = useState<"library" | "projects" | "notes">("library");
    const navigate = useNavigate();

    const { notes, projects, bookmarks, addNote: addNoteHook, deleteNote, deleteProject, deleteBookmark, addBookmark, updateNote, updateProjectProgress } = useScholarData();
    const [newNoteTitle, setNewNoteTitle] = useState("");

    const [editingNote, setEditingNote] = useState<LabNote | null>(null);
    const [viewingNote, setViewingNote] = useState<LabNote | null>(null);
    const [editContent, setEditContent] = useState("");
    const [editTitle, setEditTitle] = useState("");

    const handleAddNote = () => {
        if (!newNoteTitle.trim()) return;
        addNoteHook({ title: newNoteTitle, content: "Start writing your research notes here...", type: 'note' });
        setNewNoteTitle("");
        toast.success("Note created in Research Lab");
    };

    const handleExportNote = (note: any) => {
        const printWindow = window.open('', '_blank');
        if (!printWindow) return;
        const content = `<html><head><title>${note.title}</title><style>body{font-family:'Inter',sans-serif;padding:40px;color:#1a1a1a;max-width:800px;margin:0 auto;}h1{color:#8B5CF6;font-size:28px;border-bottom:2px solid #8B5CF6;padding-bottom:10px;}.meta{color:#666;font-size:12px;margin-bottom:30px;}.content{line-height:1.6;white-space:pre-wrap;font-size:14px;}.footer{margin-top:50px;border-top:1px solid #eee;padding-top:20px;font-size:10px;color:#999;}</style></head><body><h1>${note.title}</h1><div class="meta">Research Date: ${note.date} | Entry Type: ${note.type.toUpperCase()}</div><div class="content">${note.content}</div><div class="footer">Generated by PhD Research OS - Noble Hub Nexus</div><script>window.onload=()=>{window.print();window.close();}</script></body></html>`;
        printWindow.document.write(content);
        printWindow.document.close();
        toast.success("PDF Export engine initialized");
    };

    const handleUpdateNote = async () => {
        if (!editingNote) return;
        await updateNote(editingNote.id, { title: editTitle, content: editContent });
        setEditingNote(null);
        toast.success("Note updated successfully");
    };

    const handleSignOut = async () => {
        await supabase.auth.signOut();
        toast.success("Signed out successfully");
        navigate("/auth");
    };

    if (!session) return null;

    const user = session.user;
    const displayName = user.user_metadata?.display_name || user.email?.split("@")[0] || "User";

    return (
        <PageLayout>
            <div className="container mx-auto px-4 py-12">
                <div className="grid gap-8 lg:grid-cols-4">
                    {/* User Sidebar */}
                    <div className="lg:col-span-1">
                        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="rounded-3xl border border-border bg-card p-6 shadow-sm">
                            <div className="flex flex-col items-center text-center">
                                <div className="flex h-24 w-24 items-center justify-center rounded-full bg-primary/10 border-4 border-background shadow-xl">
                                    <User className="h-10 w-10 text-primary" />
                                </div>
                                <h2 className="mt-4 font-display text-xl font-bold text-foreground capitalize">{displayName}</h2>
                                <p className="text-sm text-muted-foreground">{user.email}</p>
                                <div className="mt-2 inline-flex items-center gap-1 rounded-full bg-amber-500/10 px-3 py-0.5 text-[10px] font-bold uppercase tracking-widest text-amber-600">Academic Member</div>
                            </div>

                            <div className="mt-6 grid grid-cols-3 gap-2 text-center">
                                <div className="rounded-xl bg-secondary/50 p-3">
                                    <p className="text-lg font-bold font-display">{notes.length}</p>
                                    <p className="text-[9px] font-bold text-muted-foreground uppercase">Notes</p>
                                </div>
                                <div className="rounded-xl bg-secondary/50 p-3">
                                    <p className="text-lg font-bold font-display">{projects.length}</p>
                                    <p className="text-[9px] font-bold text-muted-foreground uppercase">Projects</p>
                                </div>
                                <div className="rounded-xl bg-secondary/50 p-3">
                                    <p className="text-lg font-bold font-display">{bookmarks.length}</p>
                                    <p className="text-[9px] font-bold text-muted-foreground uppercase">Saved</p>
                                </div>
                            </div>

                            <div className="mt-10 space-y-1">
                                <button onClick={() => setActiveTab("library")} className={`flex w-full items-center justify-between rounded-xl px-4 py-3 text-sm font-bold transition-all ${activeTab === 'library' ? 'bg-primary/10 text-primary shadow-sm border border-primary/10' : 'text-muted-foreground hover:bg-secondary'}`}>
                                    <div className="flex items-center gap-3"><Bookmark className="h-4 w-4" /> My Library</div><ChevronRight className="h-4 w-4" />
                                </button>
                                <button onClick={() => setActiveTab("projects")} className={`flex w-full items-center justify-between rounded-xl px-4 py-3 text-sm font-bold transition-all ${activeTab === 'projects' ? 'bg-primary/10 text-primary shadow-sm border border-primary/10' : 'text-muted-foreground hover:bg-secondary'}`}>
                                    <div className="flex items-center gap-3"><FolderKanban className="h-4 w-4" /> Research Projects</div><ChevronRight className="h-4 w-4" />
                                </button>
                                <button onClick={() => setActiveTab("notes")} className={`flex w-full items-center justify-between rounded-xl px-4 py-3 text-sm font-bold transition-all ${activeTab === 'notes' ? 'bg-primary/10 text-primary shadow-sm border border-primary/10' : 'text-muted-foreground hover:bg-secondary'}`}>
                                    <div className="flex items-center gap-3"><FileEdit className="h-4 w-4" /> Lab Notes</div><ChevronRight className="h-4 w-4" />
                                </button>
                                <button className="flex w-full items-center justify-between rounded-xl px-4 py-3 text-sm font-medium text-muted-foreground transition-all hover:bg-secondary">
                                    <div className="flex items-center gap-3"><Settings className="h-4 w-4" /> Settings</div>
                                </button>
                                <button onClick={handleSignOut} className="flex w-full items-center justify-between rounded-xl px-4 py-3 text-sm font-medium text-destructive transition-all hover:bg-destructive/10">
                                    <div className="flex items-center gap-3"><LogOut className="h-4 w-4" /> Sign Out</div>
                                </button>
                            </div>
                        </motion.div>
                    </div>

                    {/* Main Content */}
                    <div className="lg:col-span-3">
                        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-8">
                            <div className="flex items-end justify-between">
                                <div>
                                    <h1 className="font-display text-3xl font-bold text-foreground">Scholar Dashboard</h1>
                                    <p className="mt-1 text-muted-foreground">Manage your saved research and scholarly interests.</p>
                                </div>
                            </div>

                            {activeTab === 'library' && (
                                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-8">
                                    <div className="grid grid-cols-3 gap-4">
                                        <div className="rounded-2xl border border-border bg-card p-4 text-center">
                                            <Award className="h-5 w-5 mx-auto text-amber-500" />
                                            <p className="mt-2 text-xl font-bold font-display">{bookmarks.filter(b => b.itemType === 'laureate').length}</p>
                                            <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Saved Laureates</p>
                                        </div>
                                        <div className="rounded-2xl border border-border bg-card p-4 text-center">
                                            <BookOpen className="h-5 w-5 mx-auto text-blue-500" />
                                            <p className="mt-2 text-xl font-bold font-display">{bookmarks.filter(b => b.itemType === 'paper').length}</p>
                                            <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Research Papers</p>
                                        </div>
                                        <div className="rounded-2xl border border-border bg-card p-4 text-center">
                                            <Video className="h-5 w-5 mx-auto text-rose-500" />
                                            <p className="mt-2 text-xl font-bold font-display">{bookmarks.filter(b => b.itemType === 'lecture').length}</p>
                                            <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Video Lectures</p>
                                        </div>
                                    </div>

                                    <div className="space-y-4">
                                        <div className="flex items-center justify-between">
                                            <h2 className="text-lg font-bold text-foreground flex items-center gap-2"><Sparkles className="h-5 w-5 text-amber-500" /> Personalized Research Feed</h2>
                                        </div>

                                        <div className="space-y-4">
                                            <div className="rounded-2xl border border-primary/20 bg-primary/5 p-6 backdrop-blur-sm">
                                                <div className="flex justify-between items-start">
                                                    <div className="flex gap-4">
                                                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center shrink-0"><Sparkles className="h-5 w-5 text-primary" /></div>
                                                        <div>
                                                            <h4 className="text-sm font-bold text-foreground">AI Insight: Breakthroughs in Quantum Computing</h4>
                                                            <p className="mt-1 text-xs text-muted-foreground leading-relaxed">Based on your interest in Physics ({bookmarks.filter(b => b.itemType === 'paper').length} saved items), we've summarized 3 recent papers on topological insulators.</p>
                                                            <div className="mt-3 flex gap-2">
                                                                <Button variant="outline" size="sm" className="h-7 text-[10px] font-bold uppercase" onClick={() => { addNoteHook({ title: "AI Insight Summary", content: "Superconductivity breakthroughs summary...", type: 'insight' }); toast.success("Summary added to Lab Notes"); }}>Add to Notes</Button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <span className="text-[10px] font-bold text-muted-foreground uppercase opacity-60">Just Now</span>
                                                </div>
                                            </div>

                                            <div className="space-y-4 pt-4">
                                                <h3 className="text-sm font-bold text-foreground flex items-center gap-2"><Bookmark className="h-4 w-4 text-primary" /> Recent Bookmarks</h3>
                                                <div className="grid gap-3">
                                                    {bookmarks.slice(0, 5).map(b => (
                                                        <div key={b.id} className="flex items-center justify-between p-3 bg-card border border-border/50 rounded-xl group">
                                                            <div className="flex items-center gap-3">
                                                                <div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center">
                                                                    {b.itemType === 'paper' ? <BookOpen className="h-4 w-4 text-primary" /> : b.itemType === 'lecture' ? <Video className="h-4 w-4 text-primary" /> : <Award className="h-4 w-4 text-primary" />}
                                                                </div>
                                                                <div>
                                                                    <p className="text-xs font-bold">{b.title}</p>
                                                                    <p className="text-[9px] uppercase font-bold text-muted-foreground">{b.itemType} · {b.date}</p>
                                                                </div>
                                                            </div>
                                                            <div className="flex items-center gap-1">
                                                                <Button variant="ghost" size="sm" className="h-7 w-7 p-0 opacity-0 group-hover:opacity-100 text-destructive hover:text-destructive" onClick={() => { deleteBookmark(b.id); toast.success("Bookmark removed"); }}>
                                                                    <Trash2 className="h-3 w-3" />
                                                                </Button>
                                                                <Button variant="ghost" size="sm" className="h-7 w-7 p-0" onClick={() => navigate(b.itemType === 'laureate' ? `/laureates/${b.itemId}` : b.itemType === 'paper' ? '/research' : '/lectures')}>
                                                                    <ChevronRight className="h-4 w-4" />
                                                                </Button>
                                                            </div>
                                                        </div>
                                                    ))}
                                                    {bookmarks.length === 0 && <p className="text-xs text-muted-foreground italic text-center py-4 bg-secondary/10 rounded-xl">No items bookmarked yet. Explore laureates, papers, and lectures to save them here.</p>}
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-12">
                                        <div className="rounded-3xl bg-gradient-to-br from-primary/10 to-transparent p-8 text-center border border-primary/10">
                                            <h3 className="text-xl font-bold text-foreground font-display">Expand Your Library</h3>
                                            <p className="mt-2 text-sm text-muted-foreground max-w-sm mx-auto">Discover groundbreaking achievements and add them to your collection.</p>
                                            <Link to="/laureates"><Button className="mt-6 rounded-xl shadow-lg shadow-primary/20">Explore Discoveries</Button></Link>
                                        </div>
                                        <div className="rounded-3xl bg-gradient-to-br from-amber-500/5 to-transparent p-8 text-center border border-amber-500/10">
                                            <h3 className="text-xl font-bold text-foreground font-display">Scholar OS Tools</h3>
                                            <p className="mt-2 text-sm text-muted-foreground max-w-sm mx-auto">Use AI-powered research tools to accelerate your PhD work.</p>
                                            <Link to="/research"><Button variant="outline" className="mt-6 rounded-xl border-amber-500/30 text-amber-600 hover:bg-amber-500/10">Open Research Archive</Button></Link>
                                        </div>
                                    </div>
                                </motion.div>
                            )}

                            {activeTab === 'notes' && (
                                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
                                    <div className="flex items-center justify-between">
                                        <h2 className="text-lg font-bold text-foreground flex items-center gap-2"><FileEdit className="h-5 w-5 text-primary" /> Research Lab Notes</h2>
                                        <div className="flex gap-2">
                                            <input className="h-9 rounded-xl bg-secondary/50 border border-border px-4 text-xs focus:ring-1 focus:ring-primary outline-none w-48 text-foreground" placeholder="Note title..." value={newNoteTitle} onChange={(e) => setNewNoteTitle(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleAddNote()} />
                                            <Button onClick={handleAddNote} size="sm" className="rounded-xl h-9"><Plus className="h-4 w-4 mr-1" /> New Note</Button>
                                        </div>
                                    </div>

                                    <div className="grid gap-4">
                                        {notes.length === 0 ? (
                                            <div className="text-center py-20 bg-secondary/20 rounded-3xl border-2 border-dashed border-border text-muted-foreground italic">No notes yet. Click 'New Note' or use Scholar Tools to auto-generate notes.</div>
                                        ) : (
                                            notes.map(note => (
                                                <div key={note.id} className="group relative rounded-2xl border border-border bg-card p-6 transition-all hover:border-primary/30">
                                                    <div className="flex justify-between items-start mb-2">
                                                        <div className="flex items-center gap-2">
                                                            <div className={`h-2 w-2 rounded-full ${note.type === 'insight' ? 'bg-amber-500' : note.type === 'breakthrough' ? 'bg-primary' : 'bg-blue-500'}`} />
                                                            <h4 className="font-bold text-foreground">{note.title}</h4>
                                                            <span className="text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-secondary text-muted-foreground">{note.type}</span>
                                                        </div>
                                                        <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                                            <span className="text-[10px] font-bold text-muted-foreground uppercase">{note.date}</span>
                                                            <button onClick={() => { deleteNote(note.id); toast.error("Note deleted"); }} className="text-destructive hover:scale-110 transition-transform"><Trash2 className="h-4 w-4" /></button>
                                                        </div>
                                                    </div>
                                                    <div className="text-xs text-muted-foreground leading-relaxed line-clamp-3 prose prose-sm max-w-none">
                                                        <ReactMarkdown>{note.content}</ReactMarkdown>
                                                    </div>
                                                    <div className="mt-4 flex gap-2">
                                                        <Button variant="ghost" size="sm" className="h-7 text-[10px] font-bold uppercase text-primary" onClick={() => { setEditingNote(note); setEditTitle(note.title); setEditContent(note.content); }}>Edit Note</Button>
                                                        <Button variant="ghost" size="sm" className="h-7 text-[10px] font-bold uppercase" onClick={() => setViewingNote(note)}>View Full</Button>
                                                        <Button variant="ghost" size="sm" className="h-7 text-[10px] font-bold uppercase" onClick={() => handleExportNote(note)}>Export PDF</Button>
                                                    </div>
                                                </div>
                                            ))
                                        )}
                                    </div>
                                </motion.div>
                            )}

                            {activeTab === 'projects' && (
                                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
                                    <div className="flex items-center justify-between">
                                        <h2 className="text-lg font-bold text-foreground flex items-center gap-2"><FolderKanban className="h-5 w-5 text-primary" /> Scientific Workspaces</h2>
                                        <Button size="sm" className="rounded-xl h-9" onClick={() => { navigate("/scientific-skills"); toast.info("Opening Research Lab to start a new project environment."); }}><Plus className="h-4 w-4 mr-1" /> New Workspace</Button>
                                    </div>

                                    <div className="grid gap-6 md:grid-cols-2">
                                        {projects.map(proj => (
                                            <div key={proj.id} className="group rounded-3xl border border-border bg-card p-6 transition-all hover:border-primary/20 hover:shadow-xl hover:shadow-primary/5">
                                                <div className="flex justify-between items-start mb-6">
                                                    <div>
                                                        <h4 className="font-bold text-foreground text-lg">{proj.name}</h4>
                                                        <span className="inline-block mt-1 px-2 py-0.5 rounded-full bg-primary/10 text-[8px] font-bold uppercase tracking-widest text-primary italic">{proj.status}</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <button onClick={() => { deleteProject(proj.id); toast.success("Project deleted"); }} className="h-8 w-8 rounded-xl flex items-center justify-center text-muted-foreground hover:text-destructive hover:bg-destructive/10 opacity-0 group-hover:opacity-100 transition-all">
                                                            <Trash2 className="h-4 w-4" />
                                                        </button>
                                                        <div className="h-10 w-10 rounded-xl bg-secondary flex items-center justify-center text-primary group-hover:bg-primary/10 transition-colors"><FolderKanban className="h-5 w-5" /></div>
                                                    </div>
                                                </div>
                                                <div className="space-y-2">
                                                    <div className="flex justify-between text-[10px] font-bold uppercase text-muted-foreground"><span>Project Progress</span><span>{proj.progress}%</span></div>
                                                    <div className="h-2 w-full bg-secondary rounded-full overflow-hidden"><motion.div className="h-full bg-primary" initial={{ width: 0 }} animate={{ width: `${proj.progress}%` }} /></div>
                                                    <div className="flex gap-2 mt-2">
                                                        {[25, 50, 75, 100].map(p => (
                                                            <button key={p} onClick={() => updateProjectProgress(proj.id, p, p === 100 ? 'Completed' : 'Active Research')} className={`text-[9px] font-bold px-2 py-1 rounded-lg border transition-all ${proj.progress >= p ? 'bg-primary/10 border-primary/20 text-primary' : 'border-border text-muted-foreground hover:border-primary/20'}`}>
                                                                {p}%
                                                            </button>
                                                        ))}
                                                    </div>
                                                </div>
                                                {proj.discovery && <p className="mt-4 text-[11px] text-muted-foreground italic line-clamp-2">"{proj.discovery}"</p>}
                                                <div className="mt-4 text-[10px] text-muted-foreground">Topic: <span className="text-primary font-bold">{proj.topic}</span> · Created: {proj.date}</div>
                                            </div>
                                        ))}

                                        <div className="rounded-3xl border-2 border-dashed border-border bg-secondary/5 flex flex-col items-center justify-center p-8 text-center transition-all hover:bg-secondary/10 cursor-pointer" onClick={() => navigate("/scientific-skills")}>
                                            <Plus className="h-10 w-10 text-muted-foreground/30 mb-2" />
                                            <h4 className="text-sm font-bold text-muted-foreground">Start New Breakthrough</h4>
                                            <p className="text-[10px] text-muted-foreground uppercase tracking-widest mt-1">Visit Lab Simulation</p>
                                        </div>
                                    </div>
                                </motion.div>
                            )}
                        </motion.div>
                    </div>
                </div>
            </div>

            {/* Edit Modal */}
            <Dialog open={!!editingNote} onOpenChange={(open) => !open && setEditingNote(null)}>
                <DialogContent className="sm:max-w-[700px] bg-card border-primary/20 rounded-3xl">
                    <DialogHeader><DialogTitle className="text-2xl font-display font-bold">Edit Research Entry</DialogTitle></DialogHeader>
                    <div className="space-y-6 py-4">
                        <div className="space-y-2">
                            <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Entry Title</label>
                            <Input value={editTitle} onChange={(e) => setEditTitle(e.target.value)} className="rounded-xl border-border bg-secondary/30" />
                        </div>
                        <div className="space-y-2">
                            <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Research Content</label>
                            <Textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} className="min-h-[300px] rounded-2xl border-border bg-secondary/30 resize-none" />
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="ghost" onClick={() => setEditingNote(null)} className="rounded-xl">Cancel</Button>
                        <Button onClick={handleUpdateNote} className="rounded-xl px-8 shadow-lg shadow-primary/20">Save Changes</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* View Full Screen Modal */}
            <Dialog open={!!viewingNote} onOpenChange={(open) => !open && setViewingNote(null)}>
                <DialogContent className="sm:max-w-[900px] h-[90vh] flex flex-col bg-slate-950 border-white/5 rounded-[3rem] p-0 overflow-hidden">
                    {viewingNote && (
                        <>
                            <div className="p-12 pb-6 border-b border-white/5">
                                <div className="flex justify-between items-start mb-6">
                                    <div className="space-y-2">
                                        <div className="flex items-center gap-3">
                                            <div className={`h-2 w-2 rounded-full shadow-[0_0_10px_rgba(139,92,246,0.5)] ${viewingNote.type === 'breakthrough' ? 'bg-primary' : viewingNote.type === 'insight' ? 'bg-amber-500' : 'bg-blue-500'}`} />
                                            <span className="text-[10px] font-black uppercase tracking-[0.3em] text-primary/70">{viewingNote.type} Entry</span>
                                        </div>
                                        <h2 className="text-4xl font-display font-bold text-white pr-12">{viewingNote.title}</h2>
                                    </div>
                                    <div className="flex gap-2">
                                        <Button variant="ghost" size="sm" className="rounded-full h-12 w-12 p-0 text-white hover:bg-white/5" onClick={() => handleExportNote(viewingNote)}><Download className="h-5 w-5" /></Button>
                                        <Button variant="ghost" size="sm" className="rounded-full h-12 w-12 p-0 text-white hover:bg-white/5" onClick={() => setViewingNote(null)}><Plus className="h-6 w-6 rotate-45" /></Button>
                                    </div>
                                </div>
                                <div className="flex gap-6 text-[10px] font-bold uppercase tracking-widest text-slate-500">
                                    <span>Created: {viewingNote.date}</span>
                                    <span>Type: {viewingNote.type}</span>
                                </div>
                            </div>
                            <div className="flex-1 overflow-y-auto p-12">
                                <div className="prose prose-invert max-w-none prose-headings:font-display prose-p:leading-relaxed prose-li:leading-relaxed">
                                    <ReactMarkdown>{viewingNote.content}</ReactMarkdown>
                                </div>
                            </div>
                            <div className="p-8 bg-black/40 border-t border-white/5 flex justify-center gap-4">
                                <Button variant="outline" className="rounded-2xl border-white/10 text-white hover:bg-white/5 px-8" onClick={() => { setEditingNote(viewingNote); setEditTitle(viewingNote.title); setEditContent(viewingNote.content); setViewingNote(null); }}>Edit Entry</Button>
                                <Button className="rounded-2xl px-12 font-black" onClick={() => setViewingNote(null)}>Close Reader</Button>
                            </div>
                        </>
                    )}
                </DialogContent>
            </Dialog>
        </PageLayout>
    );
};

export default Profile;
